/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import { MyProfile as MyProfile } from './components\my-profile\my-profile';

interface HTMLMyProfileElement extends MyProfile, HTMLElement {
}
declare var HTMLMyProfileElement: {
  prototype: HTMLMyProfileElement;
  new (): HTMLMyProfileElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-profile": HTMLMyProfileElement;
  }
  interface ElementTagNameMap {
      "my-profile": HTMLMyProfileElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-profile": JSXElements.MyProfileAttributes;
      }
  }
  namespace JSXElements {
      export interface MyProfileAttributes extends HTMLAttributes {
        
          first?: any,
          last?: any,
          photo?: any
      }
  }
}

